
class ErrorForUser(Exception):
    pass


class BadArgument(ErrorForUser):
    pass

